### ISSUE TITLE
GAL_001 Picture-Overview

### ISSUE THREAD

**Issue by Avocari** [sw19-tug/afternoon01#1]
Acceptance Criteria: 
-) all pictures displayed in a suitable size
-) scales depending on the screen-size

Description: 
As a user I want to browse through all my pictures directly after opening the app to get an overview of them.

**Comment by Cebin** [comment]
Initial implementation of picture grid done.
Requirement to close this:
* GAL_001_001 to implement scaling and fulfill acceptance criteria

**Comment by Cebin** [comment]
GAL_001_001 and GAL_001_002 are done, merged to develop.
Feature can be considered done.
